# Generated by Django 4.1.1 on 2025-12-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='meal',
            field=models.CharField(max_length=100),
        ),
    ]
